import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>This is the Homepage</h1>
        <h2>
          <Link href="/hotels">Hotels</Link>
        </h2>
        <h2>
          <Link href="/destinations">Destinations</Link>
        </h2>
      </div>
      {/* ____________________________________________________HERO */}
      <div className={styles.hero_main}>
        <div className={styles.hero_container}>
          <div className={styles.hero_title}>
            <h1>
              UNSEEN - DESTINATIONS
              <br />
              IMPOSSIBLE - ADVENTURES
            </h1>
          </div>
          <div className={styles.hero_list}>
            <ul>
              <li>
                <a href="">Lonely Planet's #1 travel destination in 2019</a>
              </li>
              <li>
                <a href="">Travel Triangle's #1 country to travel in 2022</a>
              </li>
              <li>
                <a href="">Business Insider's #13 travel destination of 2022</a>
              </li>
              <li>
                <a href="">
                  The Unconventional Route's #2 best country to travel
                </a>
              </li>
              <li>
                <a href="">World Packer's #12 world safest country to travel</a>
              </li>
            </ul>
          </div>
        </div>
        <div className={styles.hero_circle}>
          <p>100% SATISFACTION GUARANTEED</p>
        </div>
      </div>
      {/* __________________________________________________________DESCRIPTION */}
      <div className={styles.des_main}>
        <div className={styles.des_container}>
          <div className={styles.des}></div>
          <div className={styles.des_images}></div>
        </div>
      </div>
      {/* __________________________________________________________TOURS */}
      <div className={styles.tours_main}>
        <h2>TOURS</h2>
      </div>
      {/* __________________________________________________________STEPS */}
      <div className={styles.steps_main}>
        <div className={styles.steps_container}>
          <h2>PATH TO CEYLON</h2>
          <div>
            <p>STEP 1</p>
            <ul>
              <li>
                <a href="">PICK A TRAVEL DESTINATION</a>
              </li>
            </ul>
          </div>
          <div>
            <p>STEP 2</p>
            <ul>
              <li>
                <a href="">APPLY VISA ONLINE</a>
              </li>
            </ul>
          </div>
          <div>
            <p>STEP 3</p>
            <ul>
              <li>
                <a href="">BOOK A FLIGHT</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      {/* _____________________________________________________________________HOTELS */}
      <div className={styles.hotels_container}>
        <h2>POPULAR HOTELS</h2>
        <div className={styles.hotel}>
          <div className={styles.hotel_image}></div>
          <p>Hotel Name 1</p>
          <div className={styles.hotel_tags}></div>
        </div>
        <div className={styles.hotel}>
          <div className={styles.hotel_image}></div>
          <p>Hotel Name 2</p>
          <div className={styles.hotel_tags}></div>
        </div>
        <div className={styles.hotel}>
          <div className={styles.hotel_image}></div>
          <p>Hotel Name 3</p>
          <div className={styles.hotel_tags}></div>
        </div>
      </div>
      {/* ______________________________________________________________________PLACES */}
      <div className={styles.places_container}>
        <h2>POPULAR PLACES</h2>
        <div className={styles.place}>
          <div className={styles.place_image}></div>
          <div className={styles.place_dsc_holder}>place 1</div>
        </div>
        <div className={styles.place}>
          <div className={styles.place_image}></div>
          <div className={styles.place_dsc_holder}>place 2</div>
        </div>
        <div className={styles.place}>
          <div className={styles.place_image}></div>
          <div className={styles.place_dsc_holder}>place 3</div>
        </div>
      </div>
      {/* ______________________________________________________________________REVIEWS */}
      <div className={styles.review_container}>
        <div className={styles.review}>Review 1</div>
        <div className={styles.review}>Review 2</div>
        <div className={styles.review}>Review 3</div>
        <div className={styles.review}>Review 4</div>
        <div className={styles.review}>Review 5</div>
      </div>
      {/* _________________________________________________________________________FAQs */}
      <div className={styles.faq_container}>
        <h2>FAQ</h2>
        <div className={styles.faq}>
          <div className={styles.faq_question}>Question 1</div>
          <div className={styles.faq_answer}>Answer 1</div>
        </div>
        <div className={styles.faq}>
          <div className={styles.faq_question}>Question 2</div>
          <div className={styles.faq_answer}>Answer 2</div>
        </div>
        <div className={styles.faq}>
          <div className={styles.faq_question}>Question 3</div>
          <div className={styles.faq_answer}>Answer 3</div>
        </div>
        <div className={styles.faq}>
          <div className={styles.faq_question}>Question 4</div>
          <div className={styles.faq_answer}>Answer 4</div>
        </div>
      </div>
    </div>
  );
}
