import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>This is the Homepage</h1>
        <h2><Link href="/hotels">Hotels</Link></h2>
        <h2><Link href="/destinations">Destinations</Link></h2>
      </div>
    </div>
  )
}
